#!/bin/bash

# WILLIAMS %R REPORTS
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdaud_train.csv --test-data Data/test --output-folder williamssharpe --symbol usdaud
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdcad_train.csv --test-data Data/test --output-folder williamssharpe --symbol usdcad
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdchf_train.csv --test-data Data/test --output-folder williamssharpe --symbol usdchf
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdeur_train.csv --test-data Data/test --output-folder williamssharpe --symbol usdeur
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdgbp_train.csv --test-data Data/test --output-folder williamssharpe --symbol usdgbp
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdhkd_train.csv --test-data Data/test --output-folder williamssharpe --symbol usdhkd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdjpy_train.csv --test-data Data/test --output-folder williamssharpe --symbol usdjpy
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdmxn_train.csv --test-data Data/test --output-folder williamssharpe --symbol usdmxn
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdnzd_train.csv --test-data Data/test --output-folder williamssharpe --symbol usdnzd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdsek_train.csv --test-data Data/test --output-folder williamssharpe --symbol usdsek

python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdaud_train.csv --test-data Data/test --output-folder williamscagr --symbol usdaud
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdcad_train.csv --test-data Data/test --output-folder williamscagr --symbol usdcad
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdchf_train.csv --test-data Data/test --output-folder williamscagr --symbol usdchf
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdeur_train.csv --test-data Data/test --output-folder williamscagr --symbol usdeur
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdgbp_train.csv --test-data Data/test --output-folder williamscagr --symbol usdgbp
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdhkd_train.csv --test-data Data/test --output-folder williamscagr --symbol usdhkd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdjpy_train.csv --test-data Data/test --output-folder williamscagr --symbol usdjpy
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdmxn_train.csv --test-data Data/test --output-folder williamscagr --symbol usdmxn
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdnzd_train.csv --test-data Data/test --output-folder williamscagr --symbol usdnzd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy WilliamsR --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-70 lowerband_step:5 min_upperband:70 max_upperband:100 upperband_step:5" --train-data Data/train/usdsek_train.csv --test-data Data/test --output-folder williamscagr --symbol usdsek

# CCI REPORTS
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdaud_train.csv --test-data Data/test --output-folder ccisharpe --symbol usdaud
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdcad_train.csv --test-data Data/test --output-folder ccisharpe --symbol usdcad
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdchf_train.csv --test-data Data/test --output-folder ccisharpe --symbol usdchf
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdeur_train.csv --test-data Data/test --output-folder ccisharpe --symbol usdeur
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdgbp_train.csv --test-data Data/test --output-folder ccisharpe --symbol usdgbp
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdhkd_train.csv --test-data Data/test --output-folder ccisharpe --symbol usdhkd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdjpy_train.csv --test-data Data/test --output-folder ccisharpe --symbol usdjpy
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdmxn_train.csv --test-data Data/test --output-folder ccisharpe --symbol usdmxn
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdnzd_train.csv --test-data Data/test --output-folder ccisharpe --symbol usdnzd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdsek_train.csv --test-data Data/test --output-folder ccisharpe --symbol usdsek

python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdaud_train.csv --test-data Data/test --output-folder ccicagr --symbol usdaud
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdcad_train.csv --test-data Data/test --output-folder ccicagr --symbol usdcad
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdchf_train.csv --test-data Data/test --output-folder ccicagr --symbol usdchf
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdeur_train.csv --test-data Data/test --output-folder ccicagr --symbol usdeur
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdgbp_train.csv --test-data Data/test --output-folder ccicagr --symbol usdgbp
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdhkd_train.csv --test-data Data/test --output-folder ccicagr --symbol usdhkd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdjpy_train.csv --test-data Data/test --output-folder ccicagr --symbol usdjpy
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdmxn_train.csv --test-data Data/test --output-folder ccicagr --symbol usdmxn
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdnzd_train.csv --test-data Data/test --output-folder ccicagr --symbol usdnzd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy CCI --strat-args "min_period:10 max_period:20 period_step:1 min_lowerband:-100 max_lowerband:-10 lowerband_step:10" --train-data Data/train/usdsek_train.csv --test-data Data/test --output-folder ccicagr --symbol usdsek

# STOCHASTIC INDICATOR REPORTS
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdaud_train.csv --test-data Data/test --output-folder stochasticsharpe --symbol usdaud
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdchf_train.csv --test-data Data/test --output-folder stochasticsharpe --symbol usdchf
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:30 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdcad_train.csv --test-data Data/test --output-folder stochasticsharpe --symbol usdcad
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdeur_train.csv --test-data Data/test --output-folder stochasticsharpe --symbol usdeur
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdgbp_train.csv --test-data Data/test --output-folder stochasticsharpe --symbol usdgbp
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdhkd_train.csv --test-data Data/test --output-folder stochasticsharpe --symbol usdhkd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdjpy_train.csv --test-data Data/test --output-folder stochasticsharpe --symbol usdjpy
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdmxn_train.csv --test-data Data/test --output-folder stochasticsharpe --symbol usdmxn
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdnzd_train.csv --test-data Data/test --output-folder stochasticsharpe --symbol usdnzd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdsek_train.csv --test-data Data/test --output-folder stochasticsharpe --symbol usdsek

python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdaud_train.csv --test-data Data/test --output-folder stochasticcagr --symbol usdaud
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdcad_train.csv --test-data Data/test --output-folder stochasticcagr --symbol usdcad
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdchf_train.csv --test-data Data/test --output-folder stochasticcagr --symbol usdchf
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdeur_train.csv --test-data Data/test --output-folder stochasticcagr --symbol usdeur
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdgbp_train.csv --test-data Data/test --output-folder stochasticcagr --symbol usdgbp
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdhkd_train.csv --test-data Data/test --output-folder stochasticcagr --symbol usdhkd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdjpy_train.csv --test-data Data/test --output-folder stochasticcagr --symbol usdjpy
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdmxn_train.csv --test-data Data/test --output-folder stochasticcagr --symbol usdmxn
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdnzd_train.csv --test-data Data/test --output-folder stochasticcagr --symbol usdnzd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Stochastic --strat-args "min_period:2 max_period:20 period_step:1 min_lowerband:20 max_lowerband:50 lowerband_step:5 min_period_dfast:2 max_period_dfast:15 period_dfast_step:1" --train-data Data/train/usdsek_train.csv --test-data Data/test --output-folder stochasticcagr --symbol usdsek

# TURNAROUND TUESDAY REPORTS
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdaud_train.csv --test-data Data/test --output-folder turnaroundsharpe --symbol usdaud
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdcad_train.csv --test-data Data/test --output-folder turnaroundsharpe --symbol usdcad
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdchf_train.csv --test-data Data/test --output-folder turnaroundsharpe --symbol usdchf
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdeur_train.csv --test-data Data/test --output-folder turnaroundsharpe --symbol usdeur
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdgbp_train.csv --test-data Data/test --output-folder turnaroundsharpe --symbol usdgbp
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdhkd_train.csv --test-data Data/test --output-folder turnaroundsharpe --symbol usdhkd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdjpy_train.csv --test-data Data/test --output-folder turnaroundsharpe --symbol usdjpy
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdmxn_train.csv --test-data Data/test --output-folder turnaroundsharpe --symbol usdmxn
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdnzd_train.csv --test-data Data/test --output-folder turnaroundsharpe --symbol usdnzd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param sharpe --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdsek_train.csv --test-data Data/test --output-folder turnaroundsharpe --symbol usdsek

python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdaud_train.csv --test-data Data/test --output-folder turnaroundcagr --symbol usdaud
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdcad_train.csv --test-data Data/test --output-folder turnaroundcagr --symbol usdcad
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdchf_train.csv --test-data Data/test --output-folder turnaroundcagr --symbol usdchf
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdeur_train.csv --test-data Data/test --output-folder turnaroundcagr --symbol usdeur
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdgbp_train.csv --test-data Data/test --output-folder turnaroundcagr --symbol usdgbp
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdhkd_train.csv --test-data Data/test --output-folder turnaroundcagr --symbol usdhkd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdjpy_train.csv --test-data Data/test --output-folder turnaroundcagr --symbol usdjpy
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdmxn_train.csv --test-data Data/test --output-folder turnaroundcagr --symbol usdmxn
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdnzd_train.csv --test-data Data/test --output-folder turnaroundcagr --symbol usdnzd
python strategy_report.py --cash 100000 --cheat-on-open --opt-param cagr --opt-neighbors 5 --commission 0.0 --strategy Turnaround --strat-args "min_wait_days:1 max_wait_days:10 wait_days_step:1" --train-data Data/train/usdsek_train.csv --test-data Data/test --output-folder turnaroundcagr --symbol usdsek